# Generated by Django 6.0.4 on 2026-05-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_method',
            field=models.CharField(choices=[('website', 'Website Payment'), ('whatsapp', 'WhatsApp Order')], default='whatsapp', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_verification', 'Pending Verification'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('whatsapp_pending', 'WhatsApp Pending')], default='pending_verification', max_length=25),
        ),
    ]
