# Generated by Django 6.0.4 on 2026-05-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_buying_price_product_reserved_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_unisex',
            field=models.BooleanField(default=False, help_text='Display in both Men and Women sections'),
        ),
    ]
